// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizForMe.Data;

#nullable disable

namespace QuizForMe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250303044520_SchemaBase")]
    partial class SchemaBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("QuizForMe.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuxiliarImage")
                        .HasColumnType("TEXT");

                    b.Property<char>("CorrectOption")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionOfQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option_A")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option_B")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option_C")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option_D")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsToEarn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsToLost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuizID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeOfQuestion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleOfQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizForMe.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsLosted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuizDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuizTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThemeOfQuiz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailQuizPath")
                        .HasColumnType("TEXT");

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizForMe.Models.Question", b =>
                {
                    b.HasOne("QuizForMe.Models.Quiz", "QuizOwner")
                        .WithMany("Questions")
                        .HasForeignKey("QuizID");

                    b.Navigation("QuizOwner");
                });

            modelBuilder.Entity("QuizForMe.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
